#
# Converse Configuration File
#

# Can a user appeal from a ban?
canappeal: true

# URL where players should appeal their bans
banurl: https://novelmc.net

# Permissions Configuration
permissions:
  # What is the Moderator group name?
  moderator: mod

  # What is the Senior Moderator group name?
  senior_moderator: seniormod

  # What is the Developer group name?
  developer: dev

  # What is the Executive group name?
  executive: executive