name: ${project.name}
version: ${project.version}
description: Plugin for UnraveledMC
author: UnraveledMC
main: net.novelmc.Converse
depend: [LuckPerms]
api-version: 1.14
commands:
  adminchat:
    usage: /<command> <message>
    description: Talk privately with other admins
    aliases: [ac, o]
  ban:
    usage: /<command> <player> <duration> [reason]
    description: Temporarily bans a player
    aliases: [eban, banip, ebanip, tempban, etempban]
  banlookup:
    usage: /<command> <player>
    description: Look up a player ban
    aliases: [bl]
  blackchat:
    usage: /<command> <player>
    description: Makes a players chat messages show up in black.
    aliases: [darkchat, graychat]
  converse:
    usage: /<command> [reload | debug]
    description: Show information about Converse
    aliases: [tfm]
  dban:
    usage: /<command> <player> [reason]
    description: Bans a player for a day
    aliases: [dayban, gtfo]
  flatworld:
    usage: /<command>
    description: Teleport to the flatworld
    aliases: [flatlands]
  manageshop:
    usage: /<command> <add | del | set | get> <player> [amount]
    description: Manages the shop for admins.
    aliases: [mshop, shopadmin]
  mode:
    usage: /<command> [event | dev | staff | off]
    description: Change the server mode
  mute:
    usage: /<command> <player | purge>
    description: Mute a player or purge all mutes
    aliases: [stfu, emute]
  permban:
    usage: /<command> <player> [reason]
    description: Permanently bans a player.
  plotworld:
    usage: /<command>
    description: Teleport to the plotworld
  shop:
    usage: /<command> [add | set | del | get] [player] [amount]
    description: Opens the shop menu, also manages coins (Staff only).
    aliases: [umcshop]
  staff:
    usage: /<command> <add <player> <rank> | remove <player>>
    description: Manage admins
    aliases: [saconfig]
  staffworld:
    usage: /<command> <add <player> | remove <player>>
    description: Teleport to the staffworld
    aliases: [adminworld]
  unban:
    usage: /<command> <player>
    description: Unbans a banned player.
    aliases: [pardon, epardon, unpermban]
  unloadchunks:
    usage: /<command>
    description: Unloads all unused chunks
    aliases: [uc]