name: ${project.name}
version: ${project.version}
description: Plugin for NovelMC
author: Telesphoreo
main: net.novelmc.Converse
depend: [LuckPerms]
softdepend: [CoreProtect]
api-version: 1.14
commands:
  adminchat:
    usage: /<command> <message>
    description: Talk privately with other admins
    aliases: [ac, o]
  converse:
    usage: /<command> [reload | debug]
    description: Show information about Converse
    aliases: [tfm]
  flatworld:
    usage: /<command>
    description: Teleport to the flatworld
    aliases: [flatlands]
  graychat:
    usage: /<command> <player>
    description: Makes a player talk in gray chat
  mode:
    usage: /<command> [event | dev | staff | off]
    description: Change the server mode
  mute:
    usage: /<command> <player | purge>
    description: Mutes a player.
    aliases: [stfu, emute]
  permban:
    usage: /<command> <player> [reason]
    description: Permanently bans a player.
  staff:
    usage: /<command> <add <player> <rank> | remove <player>>
    description: Manage admins
    aliases: [saconfig]
  staffworld:
    usage: /<command>
    description: Teleport to the staffworld
    aliases: [adminworld]
  unpermban:
    usage: /<command> <player>
    description: Unbans a permanently banned player.