name: ${project.name}
version: ${project.version}
description: Plugin for UnraveledMC
author: UnraveledMC
main: net.novelmc.Converse
depend: [LuckPerms]
api-version: 1.14
commands:
  permban:
    usage: /<command> <player> [reason]
    description: Permanently bans a player
  plotworld:
    usage: /<command>
    description: Teleport to the plotworld
  say:
    usage: /<command> <msg>
    description: Moderator announcements
    aliases: [shout, announce, broadcast]
  shop:
    usage: /<command>
    description: Opens the shop menu.
    aliases: [umcshop]
  staff:
    usage: /<command> <add <player> <rank> | remove <player>>
    description: Manage staff members
    aliases: [saconfig]
  staffworld:
    usage: /<command> <add <player> | remove <player>>
    description: Teleport to the staffworld
    aliases: [adminworld, aw, sw]
  unban:
    usage: /<command> <player>
    description: Unbans a banned player.
    aliases: [pardon, epardon, unpermban]
  unloadchunks:
    usage: /<command>
    description: Unloads all unused chunks
    aliases: [uc]
  voterworld:
    usage: /<command>
    description: Teleport to the voterworld
    aliases: [vw]
  playtime:
    usage: /<command> [player]
    description: View player playtime
