name: ${project.name}
version: ${project.version}
description: Plugin for NovelMC
author: Telesphoreo
main: net.novelmc.Converse
depend: [LuckPerms]
softdepend: [CoreProtect]
api-version: 1.14
commands:
  adminchat:
    usage: /<command> <message>
    description: Talk privately with other admins
    aliases: [ac, o]
  ban:
    usage: /<command> <player | IP> [reason]
    description: Bans a player
    aliases: [gtfo, banip]
  converse:
    usage: /<command> [reload | debug]
    description: Show information about Converse
  staff:
    usage: /<command> <add <player> <rank> | remove <player>>
    description: Manage admins
    aliases: [saconfig]
  unban:
    usage: /<command> <player | IP>
    description: Unbans a player
    aliases: [pardon, unbanip]
permissions:
  converse.*:
    default: op
    description: If the player has OP give them everything