name: ${project.name}
version: ${project.version}
description: Plugin for NovelMC
author: Telesphoreo
main: net.novelmc.Converse
depend: [LuckPerms]
api-version: 1.14
commands:
  adminchat:
    usage: /<command> <message>
    description: Talk privately with other admins
    aliases: [ac, o]
  ban:
    usage: /<command> <player> <duration> [reason]
    description: Temporarily bans a player
    aliases: [eban, banip, ebanip]
  converse:
    usage: /<command> [reload | debug]
    description: Show information about Converse
    aliases: [tfm]
  dban:
    usage: /<command> <player> [reason]
    description: Bans a player for a day
    aliases: [dayban, gtfo]
  flatworld:
    usage: /<command>
    description: Teleport to the flatworld
    aliases: [flatlands]
  graychat:
    usage: /<command> <player>
    description: Makes a players chat messages show up in gray
  mode:
    usage: /<command> [event | dev | staff | off]
    description: Change the server mode
  mute:
    usage: /<command> <player | purge>
    description: Mute a player or purge all mutes
    aliases: [stfu, emute]
  permban:
    usage: /<command> <player> [reason]
    description: Permanently bans a player.
  plotworld:
    usage: /<command>
    description: Teleport to the plotworld
  staff:
    usage: /<command> <add <player> <rank> | remove <player>>
    description: Manage admins
    aliases: [saconfig]
  staffworld:
    usage: /<command> <add <player> | remove <player>>
    description: Teleport to the staffworld
    aliases: [adminworld]
  unban:
    usage: /<command> <player>
    description: Unbans a banned player.
    aliases: [pardon, epardon, unpermban]