name: ${project.name}
version: ${project.version}
description: Plugin for NovelMC
author: Telesphoreo
main: net.novelmc.Converse
depend: [LuckPerms]
api-version: 1.14
commands:
  converse:
    usage: /<command>
    description: Converse
  staff:
    usage: /<command> <add <player> <rank> | remove <player>>
    description: Manage admins
    aliases: [saconfig]