name: ${project.name}
version: ${project.version}
description: Plugin for PramireProXConverseVersatilityFreedomModCraft
author: Telesphoreo
main: net.novelmc.ConversePlugin
depend: [LuckPerms]
api-version: 1.14
