name: ${project.name}
version: ${project.version}
description: Plugin for NovelMC
author: Telesphoreo
main: net.novelmc.Converse
depend: [LuckPerms]
softdepend: [CoreProtect]
api-version: 1.14
commands:
  adminchat:
    usage: /<command> <message>
    description: Talk privately with other admins
    aliases: [ac, o]
  ban:
    usage: /<command> <player> [reason]
    description: Bans a player
    aliases: [gtfo, banip, eban, ebanip]
  converse:
    usage: /<command> [reload | debug]
    description: Show information about Converse
  flatworld:
    usage: /<command>
    description: Teleport to the flatworld
    aliases: [flatlands]
  mode:
    usage: /<command>
  staff:
    usage: /<command> <add <player> <rank> | remove <player>>
    description: Manage admins
    aliases: [saconfig]
  staffworld:
    usage: /<command>
    description: Teleport to the staffworld
    aliases: [adminworld]
  unban:
    usage: /<command> <player>
    description: Unbans a player
    aliases: [pardon, unbanip, eunban, eunbanip]